INSERT INTO CURRENCY_EXCHANGE VALUES (1, 'PEN', 'USD', 0.25);
INSERT INTO CURRENCY_EXCHANGE VALUES (2, 'PEN', 'EUR', 0.21);
INSERT INTO CURRENCY_EXCHANGE VALUES (3, 'PEN', 'GBP', 0.18);

INSERT INTO CURRENCY_EXCHANGE VALUES (4, 'USD', 'PEN', 3.96);
INSERT INTO CURRENCY_EXCHANGE VALUES (5, 'USD', 'EUR', 0.84);
INSERT INTO CURRENCY_EXCHANGE VALUES (6, 'USD', 'GBP', 0.72);

INSERT INTO CURRENCY_EXCHANGE VALUES (7, 'EUR', 'PEN', 4.68);
INSERT INTO CURRENCY_EXCHANGE VALUES (8, 'EUR', 'USD', 1.18);
INSERT INTO CURRENCY_EXCHANGE VALUES (9, 'EUR', 'GBP', 0.86);

INSERT INTO CURRENCY_EXCHANGE VALUES (10, 'GBP', 'PEN', 5.48);
INSERT INTO CURRENCY_EXCHANGE VALUES (11, 'GBP', 'USD', 1.38);
INSERT INTO CURRENCY_EXCHANGE VALUES (12, 'GBP', 'EUR', 1.17);