DROP TABLE IF EXISTS CURRENCY_EXCHANGE;

CREATE TABLE CURRENCY_EXCHANGE (
ID INT AUTO_INCREMENT PRIMARY KEY,
ORIGIN_CURRENCY VARCHAR(3) NOT NULL,
DESTINATION_CURRENCY VARCHAR(3) NOT NULL,
EXCHANGE_RATE DECIMAL(20, 2) NOT NULL
);